name: Kotlin CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Укажите нужную версию JDK
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests with Gradle
        run: |
          ./gradlew test --info --stacktrace
          
      - name: Count passed tests
        run: |
          echo "Counting passed tests..."
          TEST_RESULTS=$(./gradlew test --quiet --info | grep 'passed' | wc -l)
          echo "Number of passed tests: $TEST_RESULTS"
